groups:
  - gitlab
  - gitlab-admin
  - artifactory-readwrite
  - ooo

roles:
  developer:
    - gitlab
  sdet:
    - jenkins
    - prod-mergers
    - testing-sudo
  # devops:
  #   - gitlab-admin
  #   - jenkins-admin
  #   - jira-admin
  #   - dev-sudo
  #   - artifactory-readwrite
  # sysadmin:
  #   - jenkins-admin
    - prod-sudo
  # manager:


users:
  10000:
    ldap:
      uid: test.userbug
      mail: test.user0@example.com
    roles:
      - developer
  10001:
    ldap:
      uid: test.user1
      mail: test.user0@example.com
    roles:
      - developer
  10002:
    ldap:
      uid: test.user2
      mail: test.user2@example.com
    roles:
      - developer
  10003:
    ldap:
      uid: test.user3
      mail: test.user2@example.com
    roles:
      - developer
  # 10001:
  #   ldap:
  #     uid: test.user2
  #     mail: test.user20@example.com
  #   roles:
  #     - developer
  # 10002:
  #   ldap:
  #     uid: test.user3
  #     mail: test.user30@example.com
  #   roles:
  #     - developer