groups:
  - gitlab
  - gitlab-admin
  - jenkins
  - jenkins-admin
  - jira
  - jira-admin
  - marketing
  - prod-sudo
  - prod-mergers
  - testing-sudo
  - dev-sudo
  - artifactory-readonly
  - artifactory-readwrite

roles:
  developer:
    - gitlab
    - jenkins
    - jira
    - dev-sudo
    - artifactory-readonly
  sdet:
    - jenkins
    - prod-mergers
    - testing-sudo
  devops:
    - gitlab-admin
    - jenkins-admin
    - jira-admin
    - dev-sudo
    - artifactory-readwrite
  sysadmin:
    - jenkins-admin
    - prod-sudo
  manager:


users:
  10000:
    ldap:
      uid: test.user0
      mail: test.user0@example.com
    roles:
      - developer
  10001:
    ldap:
      uid: test.user1
      mail: test.user1@example.com
    roles:
      - developer