ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|

  config.vm.synced_folder "../00-config/", "/00-config", type: "rsync", rsync__exclude: ".vagrant/", rsync__auto: true
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".vagrant/", rsync__auto: true

  config.vm.define "ldap" do |ldap|
    ldap.vm.hostname = "ldap.vagrant.local"
    ldap.vm.box = "generic/centos7"
    ldap.vm.provision "shell", path: "./bootstrap-ldap.sh"
    ldap.vm.provider :libvirt do |v|
      v.memory = 1280
      v.cpus = 1
    end
  end

  # config.vm.define "ldapreset" do |ldapreset|
  #   ldapreset.vm.hostname = "ldapreset.vagrant.local"
  #   ldapreset.vm.box = "generic/centos8"
  #   ldapreset.vm.provision "shell", path: "./bootstrap-ldapreset.sh"
  #   ldapreset.vm.provider :libvirt do |v|
  #     v.memory = 356
  #     v.cpus = 1
  #   end
  # end

end