ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.define "centosldap"
  config.vm.hostname = "ldap.vagrant.local"
  config.vm.box = "generic/centos7"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".vagrant/", rsync__auto: true
  config.vm.provision "shell", path: "./bootstrap-centos.sh"
  config.vm.provider :libvirt do |v|
    v.memory = 1024
    v.cpus = 2
  end
end
