#
# Web-based tools for managing LDAP 
#
# Redirect http to https
<VirtualHost *:80>
    ServerName ldap.vagrant.local
    Redirect / https://ldap.vagrant.local/
</VirtualHost>

<VirtualHost *:443>
    ServerName ldap.vagrant.local

    DocumentRoot /usr/share
    AddDefaultCharset UTF-8

    SSLEngine on
    SSLCertificateFile /etc/pki/tls/certs/_.vagrant.local.crt
    SSLCertificateKeyFile /etc/pki/tls/certs/_.vagrant.local.key


    # self-service-password ldap

    Alias /ssp              /usr/share/self-service-password
    Alias /passwordreset    /usr/share/self-service-password
    Alias /pwdreset         /usr/share/self-service-password

    <Directory /usr/share/self-service-password>
        AllowOverride None
        Require all granted
    </Directory>

    <Directory /usr/share/self-service-password/scripts>
        AllowOverride None
        Require all denied
    </Directory>


    # ldap phpldapadmin

    Alias /phpldapadmin     /usr/share/phpldapadmin/htdocs
    Alias /ldapadmin        /usr/share/phpldapadmin/htdocs

    <Directory /usr/share/phpldapadmin/htdocs>
        AllowOverride None
        Require all granted
    </Directory>

    LogLevel debug
    ErrorLog /var/log/httpd/ldap_error_log
    CustomLog /var/log/httpd/ldap_access_log combined


    # Only hr-portal-admin

    Alias /ldapadmin        /usr/share/httpd/topsecret

    <Directory "/usr/share/httpd/topsecret">
        Options FollowSymLinks Includes
        AllowOverride None
        Order allow,deny
        Allow from all


        # -- LDAP Auth Begins Here -- #

        AuthType Basic
        AuthName "Secure Area"
        AuthzLDAPAuthoritative   On
        AuthzLDAPMethod          ldap
        AuthzLDAPProtocolVersion 3
        AuthzLDAPServer          localhost:389
        AuthzLDAPUserBase        ou=People,dc=example,dc=com
        AuthzLDAPUserKey         uid
        AuthzLDAPGroupBase       ou=Groups,dc=example,dc=com
        AuthzLDAPGroupKey        cn
        AuthzLDAPMemberKey       uniquemember
        AuthzLDAPSetGroupAuth    ldapdn
        Require group MyGroup

        # -- LDAP Auth Ends Here -- #

    </Directory>



</VirtualHost>