#
# Web-based tool for managing LDAP servers
#

# Redirect http to https
<VirtualHost *:80>
    ServerName ldap.vagrant.local
    Redirect / https://ldap.vagrant.local/

    Alias /phpldapadmin /usr/share/phpldapadmin/htdocs
    Alias /ldapadmin /usr/share/phpldapadmin/htdocs
</VirtualHost>


<Directory /usr/share/phpldapadmin/htdocs>
    AllowOverride None
    Require all granted
</Directory>


# HTTPS section
<VirtualHost *:443>
    ServerName ldap.vagrant.local

    Alias /phpldapadmin /usr/share/phpldapadmin/htdocs
    Alias /ldapadmin /usr/share/phpldapadmin/htdocs

    SSLEngine on
    SSLCertificateFile /etc/pki/tls/certs/_.vagrant.local.crt
    SSLCertificateKeyFile /etc/pki/tls/certs/_.vagrant.local.key
</VirtualHost>