[sssd]
services = nss, pam, autofs
domains = default
debug_level = 9

[domain/default]
id_provider = ldap
autofs_provider = ldap

ldap_uri = ldap://ldap.vagrant.local
ldap_search_base = dc=brambleberry,dc=local

ldap_id_use_start_tls = True
cache_credentials = True
ldap_tls_cacert = /etc/pki/tls/certs/_.vagrant.local.crt
ldap_tls_reqcert = hard
cache_credentials = True

ldap_default_bind_dn = cn=readonly,ou=system,dc=brambleberry,dc=local
ldap_default_authtok_type = password
ldap_default_authtok = thegreenHawk13579

[nss]
homedir_substring = /home

