ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'


Vagrant.configure("2") do |config|
    config.vm.hostname = "node"
    config.vm.box = "centos/7"
    config.vm.provision "shell", path: "./bootstrap.sh"
    config.vm.provision "puppet" do |puppet|
        puppet.temp_dir = "/etc/puppetlabs/vagrant"
    end
  end