# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'


boxes = [
  { :name => "master",  :ip => "172.16.8.10", :cpus => 2, :memory => 2048 },
  { :name => "node-01", :ip => "172.16.8.11", :cpus => 1, :memory => 1024 },
  { :name => "node-02", :ip => "172.16.8.12", :cpus => 1, :memory => 1024 },
]


Vagrant.configure("2") do |config|
  boxes.each do |opts|
    config.vm.define opts[:name] do |box|

      box.vm.box = "generic/ubuntu2204"

      box.vm.hostname = opts[:name]
      box.vm.network :private_network, ip: opts[:ip]

      box.vm.provider :libvirt do |vb|
        vb.cpus = opts[:cpus]
        vb.memory = opts[:memory]
      end

      box.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"

      # Add all servers to hosts file
      boxes.each do |h|
        box.vm.provision "shell", inline: "echo #{h[:ip]} #{h[:name]} >> /etc/hosts"
      end

      box.vm.provision "shell", path:"./install-kubernetes-dependencies.sh"

      if box.vm.hostname.include? "master"
        box.vm.provision "shell", path:"./configure-master-node.sh"
      end

      if box.vm.hostname.include? "node"
        box.vm.provision "shell", path:"./configure-worker-nodes.sh"
      end

    end
  end
end