apiVersion: 1

datasources:
  - name: dev-prometheus
    type: prometheus
    url: https://prometheus.vagrant.local
    basicAuth: true
    basicAuthPassword: password
    basicAuthUser: prometheusaccess
