http {
    server {
        listen              443 ssl;
        server_name         grafana.vagrant.local;
        ssl_certificate     /etc/ssl/certs/_.vagrant.local.crt;
        ssl_certificate_key /etc/ssl/private/_.vagrant.local.key;

        location / {
            proxy_pass http://localhost:3000/;
        }
    }
}

events {}