# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

if ENV['CERT_CREATION'] == 'true'

  Vagrant.configure("2") do |config|
    config.vm.define "nomad-cert-creator" do |config|
      config.vm.box = "generic/ubuntu2204"

      config.vm.hostname = "nomad-cert-creator"

      config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
    
      config.vm.provision "shell", keep_color: true, path: "init.sh"

      config.vm.provider :libvirt do |v|
        v.memory = 1512
      end
    end
  end

else

  hashistack_host_mapping = [
    'hashistack1.global=192.168.22.10',
    'hashistack2.global=192.168.22.11',
    'hashistack3.global=192.168.22.12',
  ]

  n = 3

  Vagrant.configure("2") do |config|
    (1..n).each do |i|
      config.vm.define "hashistack#{i}" do |config|

        vm_vagrant_address = hashistack_host_mapping[i-1].split('=')[1]

        config.vm.hostname = "hashistack#{i}.global"
    
        config.vm.box = "generic/ubuntu2204"
        config.vm.network "private_network", ip: vm_vagrant_address
    
        config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
      
        config.vm.provision "shell", keep_color: true, path: "init.sh", args: [hashistack_host_mapping.join(',')]

        config.vm.provider :libvirt do |v|
            v.memory = 1256
        end
      end
    end
  end

end