# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

if ENV['CERT_CREATION'] == 'true'

  Vagrant.configure("2") do |config|
    config.vm.define "nomad-cert-creator" do |config|
      config.vm.box = "generic/ubuntu2204"

      config.vm.hostname = "nomad-cert-creator"

      config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"

      config.vm.provision "shell", keep_color: true, path: "init.sh"

      config.vm.provider :libvirt do |v|
        v.memory = 1512
      end
    end
  end

else

  servers = [
    { :name => "hashistack1.global", :ip => "192.168.22.10" },
    { :name => "hashistack2.global", :ip => "192.168.22.11" },
    { :name => "hashistack3.global", :ip => "192.168.22.12" },
  ]

  n = 3

  Vagrant.configure("2") do |config|
    (0..n-1).each do |i|
      config.vm.define "hashistack#{i + 1}" do |config|

        config.vm.hostname = servers[i][:name]

        config.vm.box = "generic/ubuntu2204"
        config.vm.network "private_network", ip: servers[i][:ip]

        config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"

        # Add all servers to hosts file
        servers.each do |h|
          config.vm.provision "shell", inline: "echo #{h[:ip]} #{h[:name]} | sudo tee -a /etc/hosts"
        end

        config.vm.provision "shell", keep_color: true, path: "init.sh"

        config.vm.provider :libvirt do |v|
            v.memory = 1256
        end
      end
    end
  end

end