ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

$NOMAD_INIT = <<SCRIPT
#!/bin/bash
set -x

#yum -yq update

yum install -y yum-utils vim wget

yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
yum install -y docker-ce docker-ce-cli containerd.io
systemctl start docker

yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
yum install -yq nomad

cat <<EOF > /etc/nomad.d/nomad.hcl
data_dir = "/opt/nomad/data"
bind_addr = "$1"

server {
  enabled = true
  bootstrap_expect = 3

  server_join {
    retry_join     = [ "192.168.22.21","192.168.22.22","192.168.22.24"]
    retry_max      = 3
    retry_interval = "15s"
  }
}

client {
  enabled = true
  servers = ["192.168.22.21:4647","192.168.22.22:4647","192.168.22.23:4647"]
}

EOF

systemctl start nomad

SCRIPT


Vagrant.configure("2") do |config|
    (1..3).each do |i|
        config.vm.define "nomad#{i}" do |config|
            config.vm.hostname = "nomad#{i}"
            config.vm.box = "centos/8"
            config.vm.network "private_network", ip: "192.168.22.2#{i}"
            config.vm.provision "shell", keep_color: true, inline: $NOMAD_INIT, args: ["192.168.22.2#{i}"]
            config.vm.provider :libvirt do |v|
                v.memory = 1536
            end
        end
    end
end